schema_version: 1

context:
  name: de-marktstammdaten
  version: 0.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/de-marktstammdaten-${{ version }}.tar.gz
  sha256: 7c5d06b738a237ccfa4b7446a60cd879ee76ae4c1fd9be5b0edcd216f9d38224

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry
  run:
    - python >=${{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

tests:
  - python:
      imports:
        - deutschland.marktstammdaten
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Marktdatenstammregister API
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/bundesAPI/marktstammdaten-api

extra:
  recipe-maintainers:
    - jan-janssen
